// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Iosxe
{
    [IosxeResourceType("iosxe:iosxe/evpn:Evpn")]
    public partial class Evpn : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Advertise Default Gateway MAC/IP routes
        /// </summary>
        [Output("defaultGatewayAdvertise")]
        public Output<bool?> DefaultGatewayAdvertise { get; private set; } = null!;

        /// <summary>
        /// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being
        /// managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is.
        /// Default value is `all`. - Choices: `all`, `attributes`
        /// </summary>
        [Output("deleteMode")]
        public Output<string?> DeleteMode { get; private set; } = null!;

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;

        /// <summary>
        /// Number of IP moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Output("ipDuplicationLimit")]
        public Output<int?> IpDuplicationLimit { get; private set; } = null!;

        /// <summary>
        /// IP duplication timer - Range: `10`-`36000`
        /// </summary>
        [Output("ipDuplicationTime")]
        public Output<int?> IpDuplicationTime { get; private set; } = null!;

        /// <summary>
        /// Peer state transition logging
        /// </summary>
        [Output("loggingPeerState")]
        public Output<bool?> LoggingPeerState { get; private set; } = null!;

        /// <summary>
        /// Number of MAC moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Output("macDuplicationLimit")]
        public Output<int?> MacDuplicationLimit { get; private set; } = null!;

        /// <summary>
        /// MAC duplication timer - Range: `10`-`36000`
        /// </summary>
        [Output("macDuplicationTime")]
        public Output<int?> MacDuplicationTime { get; private set; } = null!;

        /// <summary>
        /// Ingress replication
        /// </summary>
        [Output("replicationTypeIngress")]
        public Output<bool?> ReplicationTypeIngress { get; private set; } = null!;

        /// <summary>
        /// mp2mp replication
        /// </summary>
        [Output("replicationTypeMp2mp")]
        public Output<bool?> ReplicationTypeMp2mp { get; private set; } = null!;

        /// <summary>
        /// p2mp replication
        /// </summary>
        [Output("replicationTypeP2mp")]
        public Output<bool?> ReplicationTypeP2mp { get; private set; } = null!;

        /// <summary>
        /// Static replication
        /// </summary>
        [Output("replicationTypeStatic")]
        public Output<bool?> ReplicationTypeStatic { get; private set; } = null!;

        /// <summary>
        /// Set vni-based route-target
        /// </summary>
        [Output("routeTargetAutoVni")]
        public Output<bool?> RouteTargetAutoVni { get; private set; } = null!;

        /// <summary>
        /// Loopback interface - Range: `0`-`2147483647`
        /// </summary>
        [Output("routerIdLoopback")]
        public Output<int?> RouterIdLoopback { get; private set; } = null!;


        /// <summary>
        /// Create a Evpn resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Evpn(string name, EvpnArgs? args = null, CustomResourceOptions? options = null)
            : base("iosxe:iosxe/evpn:Evpn", name, args ?? new EvpnArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Evpn(string name, Input<string> id, EvpnState? state = null, CustomResourceOptions? options = null)
            : base("iosxe:iosxe/evpn:Evpn", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Evpn resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Evpn Get(string name, Input<string> id, EvpnState? state = null, CustomResourceOptions? options = null)
        {
            return new Evpn(name, id, state, options);
        }
    }

    public sealed class EvpnArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Advertise Default Gateway MAC/IP routes
        /// </summary>
        [Input("defaultGatewayAdvertise")]
        public Input<bool>? DefaultGatewayAdvertise { get; set; }

        /// <summary>
        /// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being
        /// managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is.
        /// Default value is `all`. - Choices: `all`, `attributes`
        /// </summary>
        [Input("deleteMode")]
        public Input<string>? DeleteMode { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Number of IP moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Input("ipDuplicationLimit")]
        public Input<int>? IpDuplicationLimit { get; set; }

        /// <summary>
        /// IP duplication timer - Range: `10`-`36000`
        /// </summary>
        [Input("ipDuplicationTime")]
        public Input<int>? IpDuplicationTime { get; set; }

        /// <summary>
        /// Peer state transition logging
        /// </summary>
        [Input("loggingPeerState")]
        public Input<bool>? LoggingPeerState { get; set; }

        /// <summary>
        /// Number of MAC moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Input("macDuplicationLimit")]
        public Input<int>? MacDuplicationLimit { get; set; }

        /// <summary>
        /// MAC duplication timer - Range: `10`-`36000`
        /// </summary>
        [Input("macDuplicationTime")]
        public Input<int>? MacDuplicationTime { get; set; }

        /// <summary>
        /// Ingress replication
        /// </summary>
        [Input("replicationTypeIngress")]
        public Input<bool>? ReplicationTypeIngress { get; set; }

        /// <summary>
        /// mp2mp replication
        /// </summary>
        [Input("replicationTypeMp2mp")]
        public Input<bool>? ReplicationTypeMp2mp { get; set; }

        /// <summary>
        /// p2mp replication
        /// </summary>
        [Input("replicationTypeP2mp")]
        public Input<bool>? ReplicationTypeP2mp { get; set; }

        /// <summary>
        /// Static replication
        /// </summary>
        [Input("replicationTypeStatic")]
        public Input<bool>? ReplicationTypeStatic { get; set; }

        /// <summary>
        /// Set vni-based route-target
        /// </summary>
        [Input("routeTargetAutoVni")]
        public Input<bool>? RouteTargetAutoVni { get; set; }

        /// <summary>
        /// Loopback interface - Range: `0`-`2147483647`
        /// </summary>
        [Input("routerIdLoopback")]
        public Input<int>? RouterIdLoopback { get; set; }

        public EvpnArgs()
        {
        }
        public static new EvpnArgs Empty => new EvpnArgs();
    }

    public sealed class EvpnState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Advertise Default Gateway MAC/IP routes
        /// </summary>
        [Input("defaultGatewayAdvertise")]
        public Input<bool>? DefaultGatewayAdvertise { get; set; }

        /// <summary>
        /// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being
        /// managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is.
        /// Default value is `all`. - Choices: `all`, `attributes`
        /// </summary>
        [Input("deleteMode")]
        public Input<string>? DeleteMode { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Number of IP moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Input("ipDuplicationLimit")]
        public Input<int>? IpDuplicationLimit { get; set; }

        /// <summary>
        /// IP duplication timer - Range: `10`-`36000`
        /// </summary>
        [Input("ipDuplicationTime")]
        public Input<int>? IpDuplicationTime { get; set; }

        /// <summary>
        /// Peer state transition logging
        /// </summary>
        [Input("loggingPeerState")]
        public Input<bool>? LoggingPeerState { get; set; }

        /// <summary>
        /// Number of MAC moves within specified time interval - Range: `2`-`1000`
        /// </summary>
        [Input("macDuplicationLimit")]
        public Input<int>? MacDuplicationLimit { get; set; }

        /// <summary>
        /// MAC duplication timer - Range: `10`-`36000`
        /// </summary>
        [Input("macDuplicationTime")]
        public Input<int>? MacDuplicationTime { get; set; }

        /// <summary>
        /// Ingress replication
        /// </summary>
        [Input("replicationTypeIngress")]
        public Input<bool>? ReplicationTypeIngress { get; set; }

        /// <summary>
        /// mp2mp replication
        /// </summary>
        [Input("replicationTypeMp2mp")]
        public Input<bool>? ReplicationTypeMp2mp { get; set; }

        /// <summary>
        /// p2mp replication
        /// </summary>
        [Input("replicationTypeP2mp")]
        public Input<bool>? ReplicationTypeP2mp { get; set; }

        /// <summary>
        /// Static replication
        /// </summary>
        [Input("replicationTypeStatic")]
        public Input<bool>? ReplicationTypeStatic { get; set; }

        /// <summary>
        /// Set vni-based route-target
        /// </summary>
        [Input("routeTargetAutoVni")]
        public Input<bool>? RouteTargetAutoVni { get; set; }

        /// <summary>
        /// Loopback interface - Range: `0`-`2147483647`
        /// </summary>
        [Input("routerIdLoopback")]
        public Input<int>? RouterIdLoopback { get; set; }

        public EvpnState()
        {
        }
        public static new EvpnState Empty => new EvpnState();
    }
}
