// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Iosxe
{
    public static class GetBgpAddressFamilyIpv4Vrf
    {
        public static Task<GetBgpAddressFamilyIpv4VrfResult> InvokeAsync(GetBgpAddressFamilyIpv4VrfArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBgpAddressFamilyIpv4VrfResult>("iosxe:iosxe/getBgpAddressFamilyIpv4Vrf:getBgpAddressFamilyIpv4Vrf", args ?? new GetBgpAddressFamilyIpv4VrfArgs(), options.WithDefaults());

        public static Output<GetBgpAddressFamilyIpv4VrfResult> Invoke(GetBgpAddressFamilyIpv4VrfInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBgpAddressFamilyIpv4VrfResult>("iosxe:iosxe/getBgpAddressFamilyIpv4Vrf:getBgpAddressFamilyIpv4Vrf", args ?? new GetBgpAddressFamilyIpv4VrfInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBgpAddressFamilyIpv4VrfArgs : global::Pulumi.InvokeArgs
    {
        [Input("afName", required: true)]
        public string AfName { get; set; } = null!;

        [Input("asn", required: true)]
        public string Asn { get; set; } = null!;

        [Input("device")]
        public string? Device { get; set; }

        public GetBgpAddressFamilyIpv4VrfArgs()
        {
        }
        public static new GetBgpAddressFamilyIpv4VrfArgs Empty => new GetBgpAddressFamilyIpv4VrfArgs();
    }

    public sealed class GetBgpAddressFamilyIpv4VrfInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("afName", required: true)]
        public Input<string> AfName { get; set; } = null!;

        [Input("asn", required: true)]
        public Input<string> Asn { get; set; } = null!;

        [Input("device")]
        public Input<string>? Device { get; set; }

        public GetBgpAddressFamilyIpv4VrfInvokeArgs()
        {
        }
        public static new GetBgpAddressFamilyIpv4VrfInvokeArgs Empty => new GetBgpAddressFamilyIpv4VrfInvokeArgs();
    }


    [OutputType]
    public sealed class GetBgpAddressFamilyIpv4VrfResult
    {
        public readonly string AfName;
        public readonly string Asn;
        public readonly string? Device;
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetBgpAddressFamilyIpv4VrfVrfResult> Vrfs;

        [OutputConstructor]
        private GetBgpAddressFamilyIpv4VrfResult(
            string afName,

            string asn,

            string? device,

            string id,

            ImmutableArray<Outputs.GetBgpAddressFamilyIpv4VrfVrfResult> vrfs)
        {
            AfName = afName;
            Asn = asn;
            Device = device;
            Id = id;
            Vrfs = vrfs;
        }
    }
}
