// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Iosxe
{
    public static class GetUdld
    {
        public static Task<GetUdldResult> InvokeAsync(GetUdldArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUdldResult>("iosxe:iosxe/getUdld:getUdld", args ?? new GetUdldArgs(), options.WithDefaults());

        public static Output<GetUdldResult> Invoke(GetUdldInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUdldResult>("iosxe:iosxe/getUdld:getUdld", args ?? new GetUdldInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUdldArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public string? Device { get; set; }

        public GetUdldArgs()
        {
        }
        public static new GetUdldArgs Empty => new GetUdldArgs();
    }

    public sealed class GetUdldInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("device")]
        public Input<string>? Device { get; set; }

        public GetUdldInvokeArgs()
        {
        }
        public static new GetUdldInvokeArgs Empty => new GetUdldInvokeArgs();
    }


    [OutputType]
    public sealed class GetUdldResult
    {
        public readonly bool Aggressive;
        public readonly string? Device;
        public readonly bool Enable;
        public readonly string Id;
        public readonly int MessageTime;
        public readonly int RecoveryInterval;

        [OutputConstructor]
        private GetUdldResult(
            bool aggressive,

            string? device,

            bool enable,

            string id,

            int messageTime,

            int recoveryInterval)
        {
            Aggressive = aggressive;
            Device = device;
            Enable = enable;
            Id = id;
            MessageTime = messageTime;
            RecoveryInterval = recoveryInterval;
        }
    }
}
