// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Outputs
{

    [OutputType]
    public sealed class GetSnmpServerHostResult
    {
        /// <summary>
        /// SNMPv1/v2c community string or SNMPv3 user name
        /// </summary>
        public readonly string CommunityOrUser;
        /// <summary>
        /// Specifies an encryption type for community string
        /// </summary>
        public readonly string Encryption;
        public readonly string IpAddress;
        /// <summary>
        /// SNMP version to use for notification messages
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetSnmpServerHostResult(
            string communityOrUser,

            string encryption,

            string ipAddress,

            string version)
        {
            CommunityOrUser = communityOrUser;
            Encryption = encryption;
            IpAddress = ipAddress;
            Version = version;
        }
    }
}
