// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Outputs
{

    [OutputType]
    public sealed class PolicyMapEventClassNumberActionNumber
    {
        public readonly string? ActivateServiceTemplateConfigServiceTemplate;
        public readonly string? AuthenticateUsingMethod;
        public readonly int? AuthenticateUsingPriority;
        public readonly int? AuthenticateUsingRetries;
        public readonly int? AuthenticateUsingRetryTime;
        public readonly bool? Authorize;
        public readonly int Number;
        public readonly bool? PauseReauthentication;
        public readonly string? TerminateConfig;

        [OutputConstructor]
        private PolicyMapEventClassNumberActionNumber(
            string? activateServiceTemplateConfigServiceTemplate,

            string? authenticateUsingMethod,

            int? authenticateUsingPriority,

            int? authenticateUsingRetries,

            int? authenticateUsingRetryTime,

            bool? authorize,

            int number,

            bool? pauseReauthentication,

            string? terminateConfig)
        {
            ActivateServiceTemplateConfigServiceTemplate = activateServiceTemplateConfigServiceTemplate;
            AuthenticateUsingMethod = authenticateUsingMethod;
            AuthenticateUsingPriority = authenticateUsingPriority;
            AuthenticateUsingRetries = authenticateUsingRetries;
            AuthenticateUsingRetryTime = authenticateUsingRetryTime;
            Authorize = authorize;
            Number = number;
            PauseReauthentication = pauseReauthentication;
            TerminateConfig = terminateConfig;
        }
    }
}
