// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iosxe

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-iosxe/sdk/go/iosxe/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// This data source can read the Interface MPLS configuration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-iosxe/sdk/go/iosxe"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := iosxe.LookupInterfaceMpls(ctx, &iosxe.LookupInterfaceMplsArgs{
//				Name: "1",
//				Type: "Loopback",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupInterfaceMpls(ctx *pulumi.Context, args *LookupInterfaceMplsArgs, opts ...pulumi.InvokeOption) (*LookupInterfaceMplsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupInterfaceMplsResult
	err := ctx.Invoke("iosxe:index/getInterfaceMpls:getInterfaceMpls", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInterfaceMpls.
type LookupInterfaceMplsArgs struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	Name   string  `pulumi:"name"`
	// Interface type
	Type string `pulumi:"type"`
}

// A collection of values returned by getInterfaceMpls.
type LookupInterfaceMplsResult struct {
	// A device name from the provider configuration.
	Device *string `pulumi:"device"`
	// The path of the retrieved object.
	Id string `pulumi:"id"`
	// Configure dynamic MPLS forwarding for IP
	Ip bool `pulumi:"ip"`
	// Set MPLS Maximum Transmission Unit
	Mtu  string `pulumi:"mtu"`
	Name string `pulumi:"name"`
	// Interface type
	Type string `pulumi:"type"`
}

func LookupInterfaceMplsOutput(ctx *pulumi.Context, args LookupInterfaceMplsOutputArgs, opts ...pulumi.InvokeOption) LookupInterfaceMplsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupInterfaceMplsResult, error) {
			args := v.(LookupInterfaceMplsArgs)
			r, err := LookupInterfaceMpls(ctx, &args, opts...)
			var s LookupInterfaceMplsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupInterfaceMplsResultOutput)
}

// A collection of arguments for invoking getInterfaceMpls.
type LookupInterfaceMplsOutputArgs struct {
	// A device name from the provider configuration.
	Device pulumi.StringPtrInput `pulumi:"device"`
	Name   pulumi.StringInput    `pulumi:"name"`
	// Interface type
	Type pulumi.StringInput `pulumi:"type"`
}

func (LookupInterfaceMplsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInterfaceMplsArgs)(nil)).Elem()
}

// A collection of values returned by getInterfaceMpls.
type LookupInterfaceMplsResultOutput struct{ *pulumi.OutputState }

func (LookupInterfaceMplsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInterfaceMplsResult)(nil)).Elem()
}

func (o LookupInterfaceMplsResultOutput) ToLookupInterfaceMplsResultOutput() LookupInterfaceMplsResultOutput {
	return o
}

func (o LookupInterfaceMplsResultOutput) ToLookupInterfaceMplsResultOutputWithContext(ctx context.Context) LookupInterfaceMplsResultOutput {
	return o
}

func (o LookupInterfaceMplsResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupInterfaceMplsResult] {
	return pulumix.Output[LookupInterfaceMplsResult]{
		OutputState: o.OutputState,
	}
}

// A device name from the provider configuration.
func (o LookupInterfaceMplsResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The path of the retrieved object.
func (o LookupInterfaceMplsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Configure dynamic MPLS forwarding for IP
func (o LookupInterfaceMplsResultOutput) Ip() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) bool { return v.Ip }).(pulumi.BoolOutput)
}

// Set MPLS Maximum Transmission Unit
func (o LookupInterfaceMplsResultOutput) Mtu() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) string { return v.Mtu }).(pulumi.StringOutput)
}

func (o LookupInterfaceMplsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) string { return v.Name }).(pulumi.StringOutput)
}

// Interface type
func (o LookupInterfaceMplsResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInterfaceMplsResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInterfaceMplsResultOutput{})
}
