// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AaaAuthorizationNetwork {
    private @Nullable String a1Group;
    private String id;

    private AaaAuthorizationNetwork() {}
    public Optional<String> a1Group() {
        return Optional.ofNullable(this.a1Group);
    }
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AaaAuthorizationNetwork defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String a1Group;
        private String id;
        public Builder() {}
        public Builder(AaaAuthorizationNetwork defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.a1Group = defaults.a1Group;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder a1Group(@Nullable String a1Group) {
            this.a1Group = a1Group;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public AaaAuthorizationNetwork build() {
            final var o = new AaaAuthorizationNetwork();
            o.a1Group = a1Group;
            o.id = id;
            return o;
        }
    }
}
