// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetCryptoIkev2Result {
    private @Nullable String device;
    private Integer dpd;
    private String dpdQuery;
    private Integer dpdRetryInterval;
    private String id;
    private Integer natKeepalive;

    private GetCryptoIkev2Result() {}
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public Integer dpd() {
        return this.dpd;
    }
    public String dpdQuery() {
        return this.dpdQuery;
    }
    public Integer dpdRetryInterval() {
        return this.dpdRetryInterval;
    }
    public String id() {
        return this.id;
    }
    public Integer natKeepalive() {
        return this.natKeepalive;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCryptoIkev2Result defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String device;
        private Integer dpd;
        private String dpdQuery;
        private Integer dpdRetryInterval;
        private String id;
        private Integer natKeepalive;
        public Builder() {}
        public Builder(GetCryptoIkev2Result defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.dpd = defaults.dpd;
    	      this.dpdQuery = defaults.dpdQuery;
    	      this.dpdRetryInterval = defaults.dpdRetryInterval;
    	      this.id = defaults.id;
    	      this.natKeepalive = defaults.natKeepalive;
        }

        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder dpd(Integer dpd) {
            this.dpd = Objects.requireNonNull(dpd);
            return this;
        }
        @CustomType.Setter
        public Builder dpdQuery(String dpdQuery) {
            this.dpdQuery = Objects.requireNonNull(dpdQuery);
            return this;
        }
        @CustomType.Setter
        public Builder dpdRetryInterval(Integer dpdRetryInterval) {
            this.dpdRetryInterval = Objects.requireNonNull(dpdRetryInterval);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder natKeepalive(Integer natKeepalive) {
            this.natKeepalive = Objects.requireNonNull(natKeepalive);
            return this;
        }
        public GetCryptoIkev2Result build() {
            final var o = new GetCryptoIkev2Result();
            o.device = device;
            o.dpd = dpd;
            o.dpdQuery = dpdQuery;
            o.dpdRetryInterval = dpdRetryInterval;
            o.id = id;
            o.natKeepalive = natKeepalive;
            return o;
        }
    }
}
