// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNtpPeer {
    private String ipAddress;
    /**
     * @return Configure peer authentication key
     * 
     */
    private Integer key;
    /**
     * @return Prefer this peer when possible
     * 
     */
    private Boolean prefer;
    /**
     * @return Interface for source address
     * 
     */
    private String source;
    /**
     * @return Configure NTP version
     * 
     */
    private Integer version;

    private GetNtpPeer() {}
    public String ipAddress() {
        return this.ipAddress;
    }
    /**
     * @return Configure peer authentication key
     * 
     */
    public Integer key() {
        return this.key;
    }
    /**
     * @return Prefer this peer when possible
     * 
     */
    public Boolean prefer() {
        return this.prefer;
    }
    /**
     * @return Interface for source address
     * 
     */
    public String source() {
        return this.source;
    }
    /**
     * @return Configure NTP version
     * 
     */
    public Integer version() {
        return this.version;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNtpPeer defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ipAddress;
        private Integer key;
        private Boolean prefer;
        private String source;
        private Integer version;
        public Builder() {}
        public Builder(GetNtpPeer defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipAddress = defaults.ipAddress;
    	      this.key = defaults.key;
    	      this.prefer = defaults.prefer;
    	      this.source = defaults.source;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder ipAddress(String ipAddress) {
            this.ipAddress = Objects.requireNonNull(ipAddress);
            return this;
        }
        @CustomType.Setter
        public Builder key(Integer key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }
        @CustomType.Setter
        public Builder prefer(Boolean prefer) {
            this.prefer = Objects.requireNonNull(prefer);
            return this;
        }
        @CustomType.Setter
        public Builder source(String source) {
            this.source = Objects.requireNonNull(source);
            return this;
        }
        @CustomType.Setter
        public Builder version(Integer version) {
            this.version = Objects.requireNonNull(version);
            return this;
        }
        public GetNtpPeer build() {
            final var o = new GetNtpPeer();
            o.ipAddress = ipAddress;
            o.key = key;
            o.prefer = prefer;
            o.source = source;
            o.version = version;
            return o;
        }
    }
}
