// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPimRpCandidate {
    private Boolean bidir;
    private String groupList;
    private String interface_;
    private Integer interval;
    private Integer priority;

    private GetPimRpCandidate() {}
    public Boolean bidir() {
        return this.bidir;
    }
    public String groupList() {
        return this.groupList;
    }
    public String interface_() {
        return this.interface_;
    }
    public Integer interval() {
        return this.interval;
    }
    public Integer priority() {
        return this.priority;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPimRpCandidate defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean bidir;
        private String groupList;
        private String interface_;
        private Integer interval;
        private Integer priority;
        public Builder() {}
        public Builder(GetPimRpCandidate defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bidir = defaults.bidir;
    	      this.groupList = defaults.groupList;
    	      this.interface_ = defaults.interface_;
    	      this.interval = defaults.interval;
    	      this.priority = defaults.priority;
        }

        @CustomType.Setter
        public Builder bidir(Boolean bidir) {
            this.bidir = Objects.requireNonNull(bidir);
            return this;
        }
        @CustomType.Setter
        public Builder groupList(String groupList) {
            this.groupList = Objects.requireNonNull(groupList);
            return this;
        }
        @CustomType.Setter("interface")
        public Builder interface_(String interface_) {
            this.interface_ = Objects.requireNonNull(interface_);
            return this;
        }
        @CustomType.Setter
        public Builder interval(Integer interval) {
            this.interval = Objects.requireNonNull(interval);
            return this;
        }
        @CustomType.Setter
        public Builder priority(Integer priority) {
            this.priority = Objects.requireNonNull(priority);
            return this;
        }
        public GetPimRpCandidate build() {
            final var o = new GetPimRpCandidate();
            o.bidir = bidir;
            o.groupList = groupList;
            o.interface_ = interface_;
            o.interval = interval;
            o.priority = priority;
            return o;
        }
    }
}
