// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetVlanAccessMapResult {
    private String action;
    private @Nullable String device;
    private String id;
    private List<String> matchIpAddresses;
    private List<String> matchIpv6Addresses;
    private String name;
    private Integer sequence;

    private GetVlanAccessMapResult() {}
    public String action() {
        return this.action;
    }
    public Optional<String> device() {
        return Optional.ofNullable(this.device);
    }
    public String id() {
        return this.id;
    }
    public List<String> matchIpAddresses() {
        return this.matchIpAddresses;
    }
    public List<String> matchIpv6Addresses() {
        return this.matchIpv6Addresses;
    }
    public String name() {
        return this.name;
    }
    public Integer sequence() {
        return this.sequence;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetVlanAccessMapResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String action;
        private @Nullable String device;
        private String id;
        private List<String> matchIpAddresses;
        private List<String> matchIpv6Addresses;
        private String name;
        private Integer sequence;
        public Builder() {}
        public Builder(GetVlanAccessMapResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.device = defaults.device;
    	      this.id = defaults.id;
    	      this.matchIpAddresses = defaults.matchIpAddresses;
    	      this.matchIpv6Addresses = defaults.matchIpv6Addresses;
    	      this.name = defaults.name;
    	      this.sequence = defaults.sequence;
        }

        @CustomType.Setter
        public Builder action(String action) {
            this.action = Objects.requireNonNull(action);
            return this;
        }
        @CustomType.Setter
        public Builder device(@Nullable String device) {
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder matchIpAddresses(List<String> matchIpAddresses) {
            this.matchIpAddresses = Objects.requireNonNull(matchIpAddresses);
            return this;
        }
        public Builder matchIpAddresses(String... matchIpAddresses) {
            return matchIpAddresses(List.of(matchIpAddresses));
        }
        @CustomType.Setter
        public Builder matchIpv6Addresses(List<String> matchIpv6Addresses) {
            this.matchIpv6Addresses = Objects.requireNonNull(matchIpv6Addresses);
            return this;
        }
        public Builder matchIpv6Addresses(String... matchIpv6Addresses) {
            return matchIpv6Addresses(List.of(matchIpv6Addresses));
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder sequence(Integer sequence) {
            this.sequence = Objects.requireNonNull(sequence);
            return this;
        }
        public GetVlanAccessMapResult build() {
            final var o = new GetVlanAccessMapResult();
            o.action = action;
            o.device = device;
            o.id = id;
            o.matchIpAddresses = matchIpAddresses;
            o.matchIpv6Addresses = matchIpv6Addresses;
            o.name = name;
            o.sequence = sequence;
            return o;
        }
    }
}
