// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InterfaceTunnelIpv6Address {
    private @Nullable Boolean eui64;
    private String prefix;

    private InterfaceTunnelIpv6Address() {}
    public Optional<Boolean> eui64() {
        return Optional.ofNullable(this.eui64);
    }
    public String prefix() {
        return this.prefix;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(InterfaceTunnelIpv6Address defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean eui64;
        private String prefix;
        public Builder() {}
        public Builder(InterfaceTunnelIpv6Address defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.eui64 = defaults.eui64;
    	      this.prefix = defaults.prefix;
        }

        @CustomType.Setter
        public Builder eui64(@Nullable Boolean eui64) {
            this.eui64 = eui64;
            return this;
        }
        @CustomType.Setter
        public Builder prefix(String prefix) {
            this.prefix = Objects.requireNonNull(prefix);
            return this;
        }
        public InterfaceTunnelIpv6Address build() {
            final var o = new InterfaceTunnelIpv6Address();
            o.eui64 = eui64;
            o.prefix = prefix;
            return o;
        }
    }
}
