// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.iosxe.Utilities;
import com.pulumi.iosxe.iosxe.InterfaceLoopbackArgs;
import com.pulumi.iosxe.iosxe.inputs.InterfaceLoopbackState;
import com.pulumi.iosxe.iosxe.outputs.InterfaceLoopbackIpv6Address;
import com.pulumi.iosxe.iosxe.outputs.InterfaceLoopbackIpv6LinkLocalAddress;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="iosxe:iosxe/interfaceLoopback:InterfaceLoopback")
public class InterfaceLoopback extends com.pulumi.resources.CustomResource {
    /**
     * Set ARP cache timeout - Range: `0`-`2147483`
     * 
     */
    @Export(name="arpTimeout", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> arpTimeout;

    /**
     * @return Set ARP cache timeout - Range: `0`-`2147483`
     * 
     */
    public Output<Optional<Integer>> arpTimeout() {
        return Codegen.optional(this.arpTimeout);
    }
    /**
     * Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being
     * managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is.
     * Default value is `all`. - Choices: `all`, `attributes`
     * 
     */
    @Export(name="deleteMode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> deleteMode;

    /**
     * @return Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being
     * managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is.
     * Default value is `all`. - Choices: `all`, `attributes`
     * 
     */
    public Output<Optional<String>> deleteMode() {
        return Codegen.optional(this.deleteMode);
    }
    /**
     * Interface specific description
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Interface specific description
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    @Export(name="ipAccessGroupIn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ipAccessGroupIn;

    public Output<Optional<String>> ipAccessGroupIn() {
        return Codegen.optional(this.ipAccessGroupIn);
    }
    /**
     * inbound packets
     * 
     */
    @Export(name="ipAccessGroupInEnable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipAccessGroupInEnable;

    /**
     * @return inbound packets
     * 
     */
    public Output<Optional<Boolean>> ipAccessGroupInEnable() {
        return Codegen.optional(this.ipAccessGroupInEnable);
    }
    @Export(name="ipAccessGroupOut", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ipAccessGroupOut;

    public Output<Optional<String>> ipAccessGroupOut() {
        return Codegen.optional(this.ipAccessGroupOut);
    }
    /**
     * outbound packets
     * 
     */
    @Export(name="ipAccessGroupOutEnable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipAccessGroupOutEnable;

    /**
     * @return outbound packets
     * 
     */
    public Output<Optional<Boolean>> ipAccessGroupOutEnable() {
        return Codegen.optional(this.ipAccessGroupOutEnable);
    }
    /**
     * Enable proxy ARP
     * 
     */
    @Export(name="ipProxyArp", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipProxyArp;

    /**
     * @return Enable proxy ARP
     * 
     */
    public Output<Optional<Boolean>> ipProxyArp() {
        return Codegen.optional(this.ipProxyArp);
    }
    /**
     * Enable sending ICMP Redirect messages
     * 
     */
    @Export(name="ipRedirects", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipRedirects;

    /**
     * @return Enable sending ICMP Redirect messages
     * 
     */
    public Output<Optional<Boolean>> ipRedirects() {
        return Codegen.optional(this.ipRedirects);
    }
    /**
     * Enable sending ICMP Unreachable messages
     * 
     */
    @Export(name="ipUnreachables", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipUnreachables;

    /**
     * @return Enable sending ICMP Unreachable messages
     * 
     */
    public Output<Optional<Boolean>> ipUnreachables() {
        return Codegen.optional(this.ipUnreachables);
    }
    @Export(name="ipv4Address", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ipv4Address;

    public Output<Optional<String>> ipv4Address() {
        return Codegen.optional(this.ipv4Address);
    }
    @Export(name="ipv4AddressMask", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ipv4AddressMask;

    public Output<Optional<String>> ipv4AddressMask() {
        return Codegen.optional(this.ipv4AddressMask);
    }
    /**
     * Insert default route
     * 
     */
    @Export(name="ipv6AddressAutoconfigDefault", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipv6AddressAutoconfigDefault;

    /**
     * @return Insert default route
     * 
     */
    public Output<Optional<Boolean>> ipv6AddressAutoconfigDefault() {
        return Codegen.optional(this.ipv6AddressAutoconfigDefault);
    }
    /**
     * Obtain IPv6 address from DHCP server
     * 
     */
    @Export(name="ipv6AddressDhcp", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipv6AddressDhcp;

    /**
     * @return Obtain IPv6 address from DHCP server
     * 
     */
    public Output<Optional<Boolean>> ipv6AddressDhcp() {
        return Codegen.optional(this.ipv6AddressDhcp);
    }
    @Export(name="ipv6Addresses", refs={List.class,InterfaceLoopbackIpv6Address.class}, tree="[0,1]")
    private Output</* @Nullable */ List<InterfaceLoopbackIpv6Address>> ipv6Addresses;

    public Output<Optional<List<InterfaceLoopbackIpv6Address>>> ipv6Addresses() {
        return Codegen.optional(this.ipv6Addresses);
    }
    /**
     * Enable IPv6 on interface
     * 
     */
    @Export(name="ipv6Enable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipv6Enable;

    /**
     * @return Enable IPv6 on interface
     * 
     */
    public Output<Optional<Boolean>> ipv6Enable() {
        return Codegen.optional(this.ipv6Enable);
    }
    @Export(name="ipv6LinkLocalAddresses", refs={List.class,InterfaceLoopbackIpv6LinkLocalAddress.class}, tree="[0,1]")
    private Output</* @Nullable */ List<InterfaceLoopbackIpv6LinkLocalAddress>> ipv6LinkLocalAddresses;

    public Output<Optional<List<InterfaceLoopbackIpv6LinkLocalAddress>>> ipv6LinkLocalAddresses() {
        return Codegen.optional(this.ipv6LinkLocalAddresses);
    }
    /**
     * Set IPv6 Maximum Transmission Unit - Range: `1280`-`9976`
     * 
     */
    @Export(name="ipv6Mtu", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> ipv6Mtu;

    /**
     * @return Set IPv6 Maximum Transmission Unit - Range: `1280`-`9976`
     * 
     */
    public Output<Optional<Integer>> ipv6Mtu() {
        return Codegen.optional(this.ipv6Mtu);
    }
    /**
     * Suppress all IPv6 RA
     * 
     */
    @Export(name="ipv6NdRaSuppressAll", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ipv6NdRaSuppressAll;

    /**
     * @return Suppress all IPv6 RA
     * 
     */
    public Output<Optional<Boolean>> ipv6NdRaSuppressAll() {
        return Codegen.optional(this.ipv6NdRaSuppressAll);
    }
    /**
     * - Range: `0`-`2147483647`
     * 
     */
    @Export(name="name", refs={Integer.class}, tree="[0]")
    private Output<Integer> name;

    /**
     * @return - Range: `0`-`2147483647`
     * 
     */
    public Output<Integer> name() {
        return this.name;
    }
    /**
     * Shutdown the selected interface
     * 
     */
    @Export(name="shutdown", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> shutdown;

    /**
     * @return Shutdown the selected interface
     * 
     */
    public Output<Optional<Boolean>> shutdown() {
        return Codegen.optional(this.shutdown);
    }
    /**
     * Configure forwarding table
     * 
     */
    @Export(name="vrfForwarding", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> vrfForwarding;

    /**
     * @return Configure forwarding table
     * 
     */
    public Output<Optional<String>> vrfForwarding() {
        return Codegen.optional(this.vrfForwarding);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public InterfaceLoopback(String name) {
        this(name, InterfaceLoopbackArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public InterfaceLoopback(String name, @Nullable InterfaceLoopbackArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public InterfaceLoopback(String name, @Nullable InterfaceLoopbackArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("iosxe:iosxe/interfaceLoopback:InterfaceLoopback", name, args == null ? InterfaceLoopbackArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private InterfaceLoopback(String name, Output<String> id, @Nullable InterfaceLoopbackState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("iosxe:iosxe/interfaceLoopback:InterfaceLoopback", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static InterfaceLoopback get(String name, Output<String> id, @Nullable InterfaceLoopbackState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new InterfaceLoopback(name, id, state, options);
    }
}
