// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.iosxe.Utilities;
import com.pulumi.iosxe.iosxe.RouteMapArgs;
import com.pulumi.iosxe.iosxe.inputs.RouteMapState;
import com.pulumi.iosxe.iosxe.outputs.RouteMapEntry;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage the Route Map configuration.
 * 
 * ## Example Usage
 * 
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.iosxe.iosxe.RouteMap;
 * import com.pulumi.iosxe.iosxe.RouteMapArgs;
 * import com.pulumi.iosxe.iosxe.inputs.RouteMapEntryArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new RouteMap(&#34;example&#34;, RouteMapArgs.builder()        
 *             .entries(RouteMapEntryArgs.builder()
 *                 .continue_(false)
 *                 .description(&#34;Entry 10&#34;)
 *                 .match_as_paths_legacy(10)
 *                 .match_community_lists_legacy(&#34;COMM1&#34;)
 *                 .match_extcommunity_lists_legacy(&#34;EXTCOMM1&#34;)
 *                 .match_interfaces(&#34;Loopback1&#34;)
 *                 .match_ip_address_access_lists(&#34;ACL1&#34;)
 *                 .match_ip_next_hop_access_lists(&#34;ACL1&#34;)
 *                 .match_ipv6_address_access_lists(&#34;ACL1&#34;)
 *                 .match_ipv6_next_hop_access_lists(&#34;ACL1&#34;)
 *                 .match_local_preferences_legacy(100)
 *                 .match_route_type_external(true)
 *                 .match_route_type_external_type_1(true)
 *                 .match_route_type_external_type_2(true)
 *                 .match_route_type_internal(true)
 *                 .match_route_type_level_1(true)
 *                 .match_route_type_level_2(true)
 *                 .match_route_type_local(true)
 *                 .match_source_protocol_bgp(&#34;65000&#34;)
 *                 .match_source_protocol_connected(true)
 *                 .match_source_protocol_eigrp(&#34;10&#34;)
 *                 .match_source_protocol_isis(true)
 *                 .match_source_protocol_lisp(true)
 *                 .match_source_protocol_ospf(&#34;10&#34;)
 *                 .match_source_protocol_ospfv3(&#34;10&#34;)
 *                 .match_source_protocol_rip(true)
 *                 .match_source_protocol_static(true)
 *                 .match_tags(100)
 *                 .match_track(1)
 *                 .operation(&#34;permit&#34;)
 *                 .seq(10)
 *                 .set_as_path_prepend_as_legacy(&#34;65001 65001&#34;)
 *                 .set_as_path_prepend_last_as_legacy(5)
 *                 .set_as_path_tag_legacy(true)
 *                 .set_communities_additive_legacy(true)
 *                 .set_communities_legacy(&#34;1:2&#34;)
 *                 .set_community_list_delete_legacy(true)
 *                 .set_community_list_name_legacy(&#34;COMML1&#34;)
 *                 .set_default_interfaces(&#34;Loopback1&#34;)
 *                 .set_extcomunity_rt_legacy(&#34;10:10&#34;)
 *                 .set_extcomunity_soo_legacy(&#34;10:10&#34;)
 *                 .set_extcomunity_vpn_distinguisher_legacy(&#34;10:10&#34;)
 *                 .set_global(false)
 *                 .set_interfaces(&#34;Loopback1&#34;)
 *                 .set_ip_address(&#34;PFL1&#34;)
 *                 .set_ip_default_global_next_hop_address(&#34;1.2.3.4&#34;)
 *                 .set_ip_default_next_hop_address(&#34;1.2.3.4&#34;)
 *                 .set_ip_global_next_hop_address(&#34;1.2.3.4&#34;)
 *                 .set_ip_next_hop_address(&#34;1.2.3.4&#34;)
 *                 .set_ip_qos_group(1)
 *                 .set_ipv6_address(&#34;PFL2&#34;)
 *                 .set_ipv6_default_global_next_hop(&#34;2001::1&#34;)
 *                 .set_ipv6_default_next_hop(&#34;2001::1&#34;)
 *                 .set_ipv6_next_hop(&#34;2001::1&#34;)
 *                 .set_level_1(true)
 *                 .set_local_preference_legacy(110)
 *                 .set_metric_delay(&#34;10&#34;)
 *                 .set_metric_loading(10)
 *                 .set_metric_mtu(1500)
 *                 .set_metric_reliability(90)
 *                 .set_metric_type(&#34;external&#34;)
 *                 .set_metric_value(110)
 *                 .set_tag(100)
 *                 .set_weight_legacy(10000)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * ```sh
 *  $ pulumi import iosxe:iosxe/routeMap:RouteMap example &#34;Cisco-IOS-XE-native:native/route-map=RM1&#34;
 * ```
 * 
 */
@ResourceType(type="iosxe:iosxe/routeMap:RouteMap")
public class RouteMap extends com.pulumi.resources.CustomResource {
    /**
     * A device name from the provider configuration.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return A device name from the provider configuration.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    @Export(name="entries", refs={List.class,RouteMapEntry.class}, tree="[0,1]")
    private Output</* @Nullable */ List<RouteMapEntry>> entries;

    public Output<Optional<List<RouteMapEntry>>> entries() {
        return Codegen.optional(this.entries);
    }
    /**
     * WORD;;Route map tag
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return WORD;;Route map tag
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RouteMap(String name) {
        this(name, RouteMapArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RouteMap(String name, @Nullable RouteMapArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RouteMap(String name, @Nullable RouteMapArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("iosxe:iosxe/routeMap:RouteMap", name, args == null ? RouteMapArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private RouteMap(String name, Output<String> id, @Nullable RouteMapState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("iosxe:iosxe/routeMap:RouteMap", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RouteMap get(String name, Output<String> id, @Nullable RouteMapState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RouteMap(name, id, state, options);
    }
}
