// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iosxe

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-iosxe/sdk/go/iosxe/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupAccessListExtended(ctx *pulumi.Context, args *LookupAccessListExtendedArgs, opts ...pulumi.InvokeOption) (*LookupAccessListExtendedResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAccessListExtendedResult
	err := ctx.Invoke("iosxe:iosxe/getAccessListExtended:getAccessListExtended", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccessListExtended.
type LookupAccessListExtendedArgs struct {
	Device *string `pulumi:"device"`
	Name   string  `pulumi:"name"`
}

// A collection of values returned by getAccessListExtended.
type LookupAccessListExtendedResult struct {
	Device  *string                      `pulumi:"device"`
	Entries []GetAccessListExtendedEntry `pulumi:"entries"`
	Id      string                       `pulumi:"id"`
	Name    string                       `pulumi:"name"`
}

func LookupAccessListExtendedOutput(ctx *pulumi.Context, args LookupAccessListExtendedOutputArgs, opts ...pulumi.InvokeOption) LookupAccessListExtendedResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAccessListExtendedResult, error) {
			args := v.(LookupAccessListExtendedArgs)
			r, err := LookupAccessListExtended(ctx, &args, opts...)
			var s LookupAccessListExtendedResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupAccessListExtendedResultOutput)
}

// A collection of arguments for invoking getAccessListExtended.
type LookupAccessListExtendedOutputArgs struct {
	Device pulumi.StringPtrInput `pulumi:"device"`
	Name   pulumi.StringInput    `pulumi:"name"`
}

func (LookupAccessListExtendedOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccessListExtendedArgs)(nil)).Elem()
}

// A collection of values returned by getAccessListExtended.
type LookupAccessListExtendedResultOutput struct{ *pulumi.OutputState }

func (LookupAccessListExtendedResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccessListExtendedResult)(nil)).Elem()
}

func (o LookupAccessListExtendedResultOutput) ToLookupAccessListExtendedResultOutput() LookupAccessListExtendedResultOutput {
	return o
}

func (o LookupAccessListExtendedResultOutput) ToLookupAccessListExtendedResultOutputWithContext(ctx context.Context) LookupAccessListExtendedResultOutput {
	return o
}

func (o LookupAccessListExtendedResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupAccessListExtendedResult] {
	return pulumix.Output[LookupAccessListExtendedResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupAccessListExtendedResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAccessListExtendedResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

func (o LookupAccessListExtendedResultOutput) Entries() GetAccessListExtendedEntryArrayOutput {
	return o.ApplyT(func(v LookupAccessListExtendedResult) []GetAccessListExtendedEntry { return v.Entries }).(GetAccessListExtendedEntryArrayOutput)
}

func (o LookupAccessListExtendedResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessListExtendedResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAccessListExtendedResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessListExtendedResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAccessListExtendedResultOutput{})
}
