// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe.Iosxe.Outputs
{

    [OutputType]
    public sealed class AaaAccountingExec
    {
        public readonly string Name;
        public readonly string? StartStopGroup1;

        [OutputConstructor]
        private AaaAccountingExec(
            string name,

            string? startStopGroup1)
        {
            Name = name;
            StartStopGroup1 = startStopGroup1;
        }
    }
}
