// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe
{
    public static class GetRouteMap
    {
        /// <summary>
        /// This data source can read the Route Map configuration.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Iosxe = Pulumi.Iosxe;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Iosxe.GetRouteMap.Invoke(new()
        ///     {
        ///         Name = "RM1",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetRouteMapResult> InvokeAsync(GetRouteMapArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRouteMapResult>("iosxe:index/getRouteMap:getRouteMap", args ?? new GetRouteMapArgs(), options.WithDefaults());

        /// <summary>
        /// This data source can read the Route Map configuration.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Iosxe = Pulumi.Iosxe;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Iosxe.GetRouteMap.Invoke(new()
        ///     {
        ///         Name = "RM1",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetRouteMapResult> Invoke(GetRouteMapInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRouteMapResult>("iosxe:index/getRouteMap:getRouteMap", args ?? new GetRouteMapInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRouteMapArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public string? Device { get; set; }

        /// <summary>
        /// WORD;;Route map tag
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetRouteMapArgs()
        {
        }
        public static new GetRouteMapArgs Empty => new GetRouteMapArgs();
    }

    public sealed class GetRouteMapInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// WORD;;Route map tag
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetRouteMapInvokeArgs()
        {
        }
        public static new GetRouteMapInvokeArgs Empty => new GetRouteMapInvokeArgs();
    }


    [OutputType]
    public sealed class GetRouteMapResult
    {
        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        public readonly string? Device;
        public readonly ImmutableArray<Outputs.GetRouteMapEntryResult> Entries;
        /// <summary>
        /// The path of the retrieved object.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// WORD;;Route map tag
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetRouteMapResult(
            string? device,

            ImmutableArray<Outputs.GetRouteMapEntryResult> entries,

            string id,

            string name)
        {
            Device = device;
            Entries = entries;
            Id = id;
            Name = name;
        }
    }
}
