// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Iosxe
{
    /// <summary>
    /// This resource can manage the Username configuration.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Iosxe = Lbrlabs.PulumiPackage.Iosxe;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Iosxe.Username("example", new()
    ///     {
    ///         Description = "User1 description",
    ///         Password = "MyPassword",
    ///         PasswordEncryption = "0",
    ///         Privilege = 15,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import iosxe:index/username:Username example "Cisco-IOS-XE-native:native/username=user1"
    /// ```
    /// </summary>
    [IosxeResourceType("iosxe:index/username:Username")]
    public partial class Username : global::Pulumi.CustomResource
    {
        /// <summary>
        /// description string with max 128 characters
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// - Choices: `0`, `6`, `7`
        /// </summary>
        [Output("passwordEncryption")]
        public Output<string?> PasswordEncryption { get; private set; } = null!;

        /// <summary>
        /// Set user privilege level - Range: `0`-`15`
        /// </summary>
        [Output("privilege")]
        public Output<int?> Privilege { get; private set; } = null!;

        [Output("secret")]
        public Output<string?> Secret { get; private set; } = null!;

        /// <summary>
        /// - Choices: `0`, `5`, `8`, `9`
        /// </summary>
        [Output("secretEncryption")]
        public Output<string?> SecretEncryption { get; private set; } = null!;


        /// <summary>
        /// Create a Username resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Username(string name, UsernameArgs? args = null, CustomResourceOptions? options = null)
            : base("iosxe:index/username:Username", name, args ?? new UsernameArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Username(string name, Input<string> id, UsernameState? state = null, CustomResourceOptions? options = null)
            : base("iosxe:index/username:Username", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Username resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Username Get(string name, Input<string> id, UsernameState? state = null, CustomResourceOptions? options = null)
        {
            return new Username(name, id, state, options);
        }
    }

    public sealed class UsernameArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// description string with max 128 characters
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// - Choices: `0`, `6`, `7`
        /// </summary>
        [Input("passwordEncryption")]
        public Input<string>? PasswordEncryption { get; set; }

        /// <summary>
        /// Set user privilege level - Range: `0`-`15`
        /// </summary>
        [Input("privilege")]
        public Input<int>? Privilege { get; set; }

        [Input("secret")]
        public Input<string>? Secret { get; set; }

        /// <summary>
        /// - Choices: `0`, `5`, `8`, `9`
        /// </summary>
        [Input("secretEncryption")]
        public Input<string>? SecretEncryption { get; set; }

        public UsernameArgs()
        {
        }
        public static new UsernameArgs Empty => new UsernameArgs();
    }

    public sealed class UsernameState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// description string with max 128 characters
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// A device name from the provider configuration.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// - Choices: `0`, `6`, `7`
        /// </summary>
        [Input("passwordEncryption")]
        public Input<string>? PasswordEncryption { get; set; }

        /// <summary>
        /// Set user privilege level - Range: `0`-`15`
        /// </summary>
        [Input("privilege")]
        public Input<int>? Privilege { get; set; }

        [Input("secret")]
        public Input<string>? Secret { get; set; }

        /// <summary>
        /// - Choices: `0`, `5`, `8`, `9`
        /// </summary>
        [Input("secretEncryption")]
        public Input<string>? SecretEncryption { get; set; }

        public UsernameState()
        {
        }
        public static new UsernameState Empty => new UsernameState();
    }
}
