// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InterfaceNveVniVrfArgs extends com.pulumi.resources.ResourceArgs {

    public static final InterfaceNveVniVrfArgs Empty = new InterfaceNveVniVrfArgs();

    @Import(name="vniRange", required=true)
    private Output<String> vniRange;

    public Output<String> vniRange() {
        return this.vniRange;
    }

    @Import(name="vrf")
    private @Nullable Output<String> vrf;

    public Optional<Output<String>> vrf() {
        return Optional.ofNullable(this.vrf);
    }

    private InterfaceNveVniVrfArgs() {}

    private InterfaceNveVniVrfArgs(InterfaceNveVniVrfArgs $) {
        this.vniRange = $.vniRange;
        this.vrf = $.vrf;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InterfaceNveVniVrfArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InterfaceNveVniVrfArgs $;

        public Builder() {
            $ = new InterfaceNveVniVrfArgs();
        }

        public Builder(InterfaceNveVniVrfArgs defaults) {
            $ = new InterfaceNveVniVrfArgs(Objects.requireNonNull(defaults));
        }

        public Builder vniRange(Output<String> vniRange) {
            $.vniRange = vniRange;
            return this;
        }

        public Builder vniRange(String vniRange) {
            return vniRange(Output.of(vniRange));
        }

        public Builder vrf(@Nullable Output<String> vrf) {
            $.vrf = vrf;
            return this;
        }

        public Builder vrf(String vrf) {
            return vrf(Output.of(vrf));
        }

        public InterfaceNveVniVrfArgs build() {
            $.vniRange = Objects.requireNonNull($.vniRange, "expected parameter 'vniRange' to be non-null");
            return $;
        }
    }

}
