// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class LoggingIpv4HostArgs extends com.pulumi.resources.ResourceArgs {

    public static final LoggingIpv4HostArgs Empty = new LoggingIpv4HostArgs();

    @Import(name="ipv4Host", required=true)
    private Output<String> ipv4Host;

    public Output<String> ipv4Host() {
        return this.ipv4Host;
    }

    private LoggingIpv4HostArgs() {}

    private LoggingIpv4HostArgs(LoggingIpv4HostArgs $) {
        this.ipv4Host = $.ipv4Host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LoggingIpv4HostArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LoggingIpv4HostArgs $;

        public Builder() {
            $ = new LoggingIpv4HostArgs();
        }

        public Builder(LoggingIpv4HostArgs defaults) {
            $ = new LoggingIpv4HostArgs(Objects.requireNonNull(defaults));
        }

        public Builder ipv4Host(Output<String> ipv4Host) {
            $.ipv4Host = ipv4Host;
            return this;
        }

        public Builder ipv4Host(String ipv4Host) {
            return ipv4Host(Output.of(ipv4Host));
        }

        public LoggingIpv4HostArgs build() {
            $.ipv4Host = Objects.requireNonNull($.ipv4Host, "expected parameter 'ipv4Host' to be non-null");
            return $;
        }
    }

}
