// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class LoggingIpv6HostArgs extends com.pulumi.resources.ResourceArgs {

    public static final LoggingIpv6HostArgs Empty = new LoggingIpv6HostArgs();

    @Import(name="ipv6Host", required=true)
    private Output<String> ipv6Host;

    public Output<String> ipv6Host() {
        return this.ipv6Host;
    }

    private LoggingIpv6HostArgs() {}

    private LoggingIpv6HostArgs(LoggingIpv6HostArgs $) {
        this.ipv6Host = $.ipv6Host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LoggingIpv6HostArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LoggingIpv6HostArgs $;

        public Builder() {
            $ = new LoggingIpv6HostArgs();
        }

        public Builder(LoggingIpv6HostArgs defaults) {
            $ = new LoggingIpv6HostArgs(Objects.requireNonNull(defaults));
        }

        public Builder ipv6Host(Output<String> ipv6Host) {
            $.ipv6Host = ipv6Host;
            return this;
        }

        public Builder ipv6Host(String ipv6Host) {
            return ipv6Host(Output.of(ipv6Host));
        }

        public LoggingIpv6HostArgs build() {
            $.ipv6Host = Objects.requireNonNull($.ipv6Host, "expected parameter 'ipv6Host' to be non-null");
            return $;
        }
    }

}
