// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SnmpServerSnmpCommunityArgs extends com.pulumi.resources.ResourceArgs {

    public static final SnmpServerSnmpCommunityArgs Empty = new SnmpServerSnmpCommunityArgs();

    @Import(name="accessListName")
    private @Nullable Output<String> accessListName;

    public Optional<Output<String>> accessListName() {
        return Optional.ofNullable(this.accessListName);
    }

    @Import(name="ipv6")
    private @Nullable Output<String> ipv6;

    public Optional<Output<String>> ipv6() {
        return Optional.ofNullable(this.ipv6);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="permission")
    private @Nullable Output<String> permission;

    public Optional<Output<String>> permission() {
        return Optional.ofNullable(this.permission);
    }

    @Import(name="view")
    private @Nullable Output<String> view;

    public Optional<Output<String>> view() {
        return Optional.ofNullable(this.view);
    }

    private SnmpServerSnmpCommunityArgs() {}

    private SnmpServerSnmpCommunityArgs(SnmpServerSnmpCommunityArgs $) {
        this.accessListName = $.accessListName;
        this.ipv6 = $.ipv6;
        this.name = $.name;
        this.permission = $.permission;
        this.view = $.view;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SnmpServerSnmpCommunityArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SnmpServerSnmpCommunityArgs $;

        public Builder() {
            $ = new SnmpServerSnmpCommunityArgs();
        }

        public Builder(SnmpServerSnmpCommunityArgs defaults) {
            $ = new SnmpServerSnmpCommunityArgs(Objects.requireNonNull(defaults));
        }

        public Builder accessListName(@Nullable Output<String> accessListName) {
            $.accessListName = accessListName;
            return this;
        }

        public Builder accessListName(String accessListName) {
            return accessListName(Output.of(accessListName));
        }

        public Builder ipv6(@Nullable Output<String> ipv6) {
            $.ipv6 = ipv6;
            return this;
        }

        public Builder ipv6(String ipv6) {
            return ipv6(Output.of(ipv6));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder permission(@Nullable Output<String> permission) {
            $.permission = permission;
            return this;
        }

        public Builder permission(String permission) {
            return permission(Output.of(permission));
        }

        public Builder view(@Nullable Output<String> view) {
            $.view = view;
            return this;
        }

        public Builder view(String view) {
            return view(Output.of(view));
        }

        public SnmpServerSnmpCommunityArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
