// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.iosxe.iosxe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SystemMulticastRoutingVrfArgs extends com.pulumi.resources.ResourceArgs {

    public static final SystemMulticastRoutingVrfArgs Empty = new SystemMulticastRoutingVrfArgs();

    @Import(name="distributed")
    private @Nullable Output<Boolean> distributed;

    public Optional<Output<Boolean>> distributed() {
        return Optional.ofNullable(this.distributed);
    }

    @Import(name="vrf", required=true)
    private Output<String> vrf;

    public Output<String> vrf() {
        return this.vrf;
    }

    private SystemMulticastRoutingVrfArgs() {}

    private SystemMulticastRoutingVrfArgs(SystemMulticastRoutingVrfArgs $) {
        this.distributed = $.distributed;
        this.vrf = $.vrf;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SystemMulticastRoutingVrfArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SystemMulticastRoutingVrfArgs $;

        public Builder() {
            $ = new SystemMulticastRoutingVrfArgs();
        }

        public Builder(SystemMulticastRoutingVrfArgs defaults) {
            $ = new SystemMulticastRoutingVrfArgs(Objects.requireNonNull(defaults));
        }

        public Builder distributed(@Nullable Output<Boolean> distributed) {
            $.distributed = distributed;
            return this;
        }

        public Builder distributed(Boolean distributed) {
            return distributed(Output.of(distributed));
        }

        public Builder vrf(Output<String> vrf) {
            $.vrf = vrf;
            return this;
        }

        public Builder vrf(String vrf) {
            return vrf(Output.of(vrf));
        }

        public SystemMulticastRoutingVrfArgs build() {
            $.vrf = Objects.requireNonNull($.vrf, "expected parameter 'vrf' to be non-null");
            return $;
        }
    }

}
