// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This data source can read the Radius Server configuration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as iosxe from "@pulumi/iosxe";
 *
 * const example = iosxe.getRadiusServer({});
 * ```
 */
export function getRadiusServer(args?: GetRadiusServerArgs, opts?: pulumi.InvokeOptions): Promise<GetRadiusServerResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("iosxe:index/getRadiusServer:getRadiusServer", {
        "device": args.device,
    }, opts);
}

/**
 * A collection of arguments for invoking getRadiusServer.
 */
export interface GetRadiusServerArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: string;
}

/**
 * A collection of values returned by getRadiusServer.
 */
export interface GetRadiusServerResult {
    /**
     * Customize selected radius attributes
     */
    readonly attributes: outputs.GetRadiusServerAttribute[];
    /**
     * The time during which no properly formed response must be received from the RADIUS server
     */
    readonly deadCriteriaTime: number;
    /**
     * The number of times the router must fail to receive a response from the radius server to mark it as dead
     */
    readonly deadCriteriaTries: number;
    /**
     * Time to stop using a server that does not respond
     */
    readonly deadtime: number;
    /**
     * A device name from the provider configuration.
     */
    readonly device?: string;
    /**
     * The path of the retrieved object.
     */
    readonly id: string;
}
/**
 * This data source can read the Radius Server configuration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as iosxe from "@pulumi/iosxe";
 *
 * const example = iosxe.getRadiusServer({});
 * ```
 */
export function getRadiusServerOutput(args?: GetRadiusServerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRadiusServerResult> {
    return pulumi.output(args).apply((a: any) => getRadiusServer(a, opts))
}

/**
 * A collection of arguments for invoking getRadiusServer.
 */
export interface GetRadiusServerOutputArgs {
    /**
     * A device name from the provider configuration.
     */
    device?: pulumi.Input<string>;
}
